// Public schema barrel, drizzle-kit reads from here; runtime imports use it
// as the single entry into the DB layer.
export * from "./_shared";
// BetterAuth-owned identity tables (user, session, account, verification)
// + role text column (DEC-003 additionalFields). Generated by
// `bunx @better-auth/cli generate`.
export * from "./_auth";
export * from "./catalog";
export * from "./warehouses";
export * from "./products";
export * from "./movements";
export * from "./purchase-orders";
export * from "./audit";
export * from "./settings";
