import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "@/db/client";

/**
 * BetterAuth server instance — single source of truth for sessions, sign-up
 * /sign-in, password hashing, and rate-limited credential checks.
 *
 * Per DEC-003:
 *   - email + password (no magic-link in MVP)
 *   - Postgres-stored sessions (revocable)
 *   - 7-day sliding window (refreshed on use)
 *   - 5 attempts / 15 min rate limit on credential endpoints
 *
 * The DB schema for BetterAuth's required tables (user, session, account,
 * verification) is generated by `bunx @better-auth/cli generate` and lives
 * under src/db/schema/_auth.ts (Phase 2.2 follow-up).
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, { provider: "pg" }),
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    minPasswordLength: 8,
    requireEmailVerification: false,
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        required: false,
        defaultValue: "staff",
        input: false, // not user-settable during sign-up; only admin promotes
      },
    },
  },
  session: {
    expiresIn: 60 * 60 * 24 * 7, // 7d
    updateAge: 60 * 60 * 24, // refresh window every 24h of use
    cookieCache: { enabled: true, maxAge: 5 * 60 },
  },
  rateLimit: {
    // Mirrors BetterAuth's own default (`?? isProduction`): throttle the public
    // credential endpoints in prod only. Forcing it on in dev/test trips the
    // E2E suite — multiple parallel sign-ins from 127.0.0.1 exceed 5/15min and
    // get 429'd, which looks like a broken sign-in. DEC-003 R2 wanted strict
    // prod rate limiting; this keeps that while letting trusted-IP CI run clean.
    enabled: process.env.NODE_ENV === "production",
    window: 60 * 15, // 15 min
    max: 5,
  },
  advanced: {
    cookiePrefix: "crate",
  },
});

export type Auth = typeof auth;
export type Session = Auth["$Infer"]["Session"];
