import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { db } from "@/db/client";
import { credentialRateLimitRules } from "./rate-limit";

/**
 * BetterAuth server instance — single source of truth for sessions, sign-up
 * /sign-in, password hashing, and rate-limited credential checks.
 *
 * Per DEC-003 / DEC-028:
 *   - email + password (no magic-link in MVP)
 *   - Postgres-stored sessions (revocable)
 *   - 7-day sliding window (refreshed on use)
 *   - credential endpoint (`/sign-in/email`) capped at 10 attempts / 15 min per
 *     IP in prod via `customRules` (DEC-028) — this OVERRIDES better-auth's
 *     built-in 3/10s `/sign-in` special rule, which alone permits ~1080/hr/IP.
 *     The top-level `window/max` below is the global default for OTHER auth
 *     paths (get-session, sign-out); it does NOT govern sign-in.
 *
 * The DB schema for BetterAuth's required tables (user, session, account,
 * verification) is generated by `bunx @better-auth/cli generate` and lives
 * under src/db/schema/_auth.ts (Phase 2.2 follow-up).
 */
export const auth = betterAuth({
  database: drizzleAdapter(db, { provider: "pg" }),
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    minPasswordLength: 8,
    requireEmailVerification: false,
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        required: false,
        defaultValue: "staff",
        input: false, // not user-settable during sign-up; only admin promotes
      },
    },
  },
  session: {
    expiresIn: 60 * 60 * 24 * 7, // 7d
    updateAge: 60 * 60 * 24, // refresh window every 24h of use
    cookieCache: { enabled: true, maxAge: 5 * 60 },
  },
  rateLimit: {
    // Prod-only (mirrors better-auth's own `?? isProduction` default): forcing
    // it on in dev/test trips the E2E suite — parallel sign-ins from 127.0.0.1
    // would 429 and look like a broken sign-in. `customRules` (DEC-028) caps the
    // credential endpoint; `window/max` here is only the global default for
    // non-special auth paths (e.g. get-session, sign-out). NB: server-side
    // session reads call `auth.api.getSession()` directly and bypass this HTTP
    // limiter, so the global 5/15min does not throttle normal page loads.
    enabled: process.env.NODE_ENV === "production",
    window: 60 * 15, // 15 min
    max: 5,
    customRules: credentialRateLimitRules,
  },
  advanced: {
    cookiePrefix: "crate",
  },
});

export type Auth = typeof auth;
export type Session = Auth["$Infer"]["Session"];
